### ISSUE TITLE
Broker cluster never successfully updates after updating operator from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by clive-jevons** [emqx/emqx-operator#897]
**Describe the bug**
We have multiple EMQX clusters deployed using the emqx-operator v2.1.4.  
On our DEV cluster I updated the operator to v2.2.0 and watched the Pods. The new STS and Pod for the core node was created (on DEV it's a small broker cluster with only 1 core and 1 replicant). The new core node Pod is created and shows as ready in `kubectl get pod`, but the STS never shows it as ready because the `apps.emqx.io/on-serving` condition is never set (at all).  
When I check the EMQX dashboard I can, however, actually see the new core node and everything looks green there for it. Also, there are no errors in the Pod logs of the new core node.

AFAICT the code which is responsible for creating and then updating that condition (methods `updatePodConditions#reconcile` and `updatePodConditions#checkInCluster`) checks the `.status.coreNodes` field of the `EMQX` resource. When I look at that resource in the cluster, it does _not_ have that field at all.

The original `EMQX` resource was created in version `apps.emqx.io/v2alpha1` but, of course, was updated in-cluster to `apps.emqx.io/v2beta1` during the upgrade of the operator. Not sure if that plays a role.

I haven't looked any deeper into why `status.coreNodes` is missing in the `EMQX` resource yet.

**To Reproduce**
Provision `emqx-operator` in version 2.1.4. Provision a small EMQX broker cluster using API version `apps.emqx.io/v2alpha1`, setting both core and replicants count to 1 and using EMQX image version `emqx:5.0.23`.

Then upgrade the operator to version 2.2.0 and watch the STS and Pods.

**Expected behavior**
Core nodes are updated successfully.

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: `v1.24.10`
- Cloud-provider/provisioner: MS AKS
- emqx-operator version: 2.1.4 / 2.2.0
- Install method: Helm

**Comment by Rory-Z** [comment]
Hi， @clive-jevons EMQX Operator 2.2.0 just support EMQX 5.1.1 and later, could you please try upgrade EMQX version and retry

**Comment by clive-jevons** [comment]
Hi @Rory-Z ,
Thanks for the info ... would you recommend first upgrading the broker to 5.1.1 and then the operator to 2.2.0, or the other way round?

**Comment by tollercode** [comment]
Experiencing the same behavior. 

Setup: Operator 2.2.0 + Broker 5.1.1

Readiness probes on core-nodes are failing with connection refused

**Comment by Rory-Z** [comment]
> Experiencing the same behavior.经历同样的行为。
> 
> Setup: Operator 2.2.0 + Broker 5.1.1设置：Operator 2.2.0 + Broker 5.1.1
> 
> Readiness probes on core-nodes are failing with connection refused核心节点上的就绪探测失败，连接被拒绝

Hi @tollercode Could you please change readiness probe and retry it ? It's in `spec.coreTemaplte.spec.readinessProbe`.

If still failed, please show the log of the core pod

**Comment by Rory-Z** [comment]
Hi, @clive-jevons Some `connect: connection refused ` is normal, because the EMQX will restart when it join cluster, could you please tell me more detailed information?

**Comment by tollercode** [comment]
@Rory-Z after editing Readiness-Probe I get following state:

`Corresponding condition of pod readiness gate "apps.emqx.io/on-serving" does not exist`

`EMQX_API_KEY__BOOTSTRAP_FILE [api_key.bootstrap_file]: /opt/emqx/data/bootstrap_api_key
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_CLUSTER__DNS__RECORD_TYPE [cluster.dns.record_type]: srv
EMQX_CLUSTER__DNS__NAME [cluster.dns.name]: emqx-cluster-headless.dev.svc.cluster.local
EMQX_CLUSTER__DISCOVERY_STRATEGY [cluster.discovery_strategy]: dns
EMQX_NODE__ROLE [node.role]: core
EMQX_NODE__DATA_DIR [node.data_dir]: dataEMQX_NODE__COOKIE [node.cookie]: ******
EMQX_NODE__NAME [node.name]: emqx@emqx-cluster-core-56db94994-0.emqx-cluster-headless.dev.svc.cluster.local
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.

EMQX Enterprise 5.1.1 is running now!`

**Comment by Rory-Z** [comment]
The readiness gate `apps.emqx.io/on-serving` will be ready after joining the cluster node, you can check EMQX cluster nodes by `emqx ctl cluster status` or `kuebctl get emqx $name -o json | jq .status.coreNodes` and `kuebctl get emqx $name -o json | jq .status.replicantNodes`.
If use EMQX Enterprise,  `apps.emqx.io/on-serving` will also check if `Get api/v5/load_rebalance/availability_check` returns 200.
Could you please check them

**Comment by tollercode** [comment]
@Rory-Z 

Executing this gives:

```
Cluster status: #{running_nodes =>
                      ['emqx@emqx-cluster-core-56db94994-0.emqx-cluster-headless.dev.svc.cluster.local',
                       'emqx@emqx-cluster-core-56db94994-1.emqx-cluster-headless.dev.svc.cluster.local'],
                  stopped_nodes => []}
```

```
NAME           STATUS                 AGE
emqx-cluster   CoreNodesProgressing   11h
```

Calling Get api/v5/load_rebalance/availability_check returns 200 OK. 
Strangely I can also connect to the cluster dashboard and it seems to run fine.

**Comment by Rory-Z** [comment]
@tollercode Could you please open Operator's debug log and share it with me?
you can append `--zap-devel=true` to EMQX Operator container's args, and check EMQX Operator log

And please let me know your EMQX customer resource YAML file

**Comment by tollercode** [comment]
@Rory-Z 
Logs:
[manager.txt](https://github.com/emqx/emqx-operator/files/12290082/manager.txt)

Manifest:
``` yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx-cluster
  labels: {
    emqx-cluster: emqx-cluster
  }
spec:
  config:
      data: |
        dashboard.listeners.http.bind = 18083
        mqtt {
          peer_cert_as_clientid = "cn"
        }
        listeners.ssl.default {
          bind = "0.0.0.0:8883"
          ssl_options.verify = verify_peer
          ssl_options {
            cacertfile = "/mounted/cert/ca.crt"
            certfile = "/mounted/cert/tls.crt"
            keyfile = "/mounted/cert/tls.key"
          }
        }
  image: "emqx/emqx-enterprise:5.1.1"
  imagePullPolicy: IfNotPresent
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: azurefile
        resources:
          requests:
            storage: 20Mi
        accessModes:
        - ReadWriteOnce
      replicas: 2
      toleRations:
        - key: workload
          operator: Equal
          value: mqtt
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - mqtt
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Try not to co-locate with nodes from the same cluster
            - weight: 60
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: emqx-cluster
                      operator: In
                      values:
                        - emqx-cluster
                topologyKey: "kubernetes.io/hostname"     
      extraVolumes:
         - name: emqx-tls
           secret:
             secretName: emqx-tls
      extraVolumeMounts:
         - name: emqx-tls
           mountPath: /mounted/cert
  replicantTemplate:
    spec:
      replicas: 0
      extraVolumes:
         - name: emqx-tls
           secret:
             secretName: emqx-tls
      extraVolumeMounts:
         - name: emqx-tls
           mountPath: /mounted/cert
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
    spec:
      type: ClusterIP
      selector:
        apps.emqx.io/db-role: core
      ports:
        - name: "dashboard-listeners-http-bind"
          protocol: TCP
          port: 18083
          targetPort: 18083
  listenersServiceTemplate:
    metadata:
      name: emqx-tls-listener
    spec:
      type: LoadBalancer
      ports:
        - name: "ssl-default"
          protocol: TCP
          port: 8883
          targetPort: 8883
```

**Comment by tollercode** [comment]
I think it is also related to the VolumeClaim Problem

**Comment by tollercode** [comment]
@Rory-Z trying with 2.2.1-rc.1 I get the following log lines:

Log for VolumeClaim issues disappeared as expected, still the 2 core-nodes do not become ready. Went through your checks and cluster seems fine.
If I Port-Forward the Dashboard to my localhost I can reach the cluster and it behaves fine. Even pub/sub of messages works

**Comment by Rory-Z** [comment]
@tollercode Could you please check EMQX Operator debug logs

**Comment by tollercode** [comment]
This is what I get,no more logs:

```
2023-08-09T06:52:08Z	INFO	emqx-resource	default	{"name": "emqx-cluster"}
2023-08-09T06:52:08Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-apps-emqx-io-v2beta1-emqx", "code": 200, "reason": "", "UID": "27d75065-f965-4ce3-8528-b5315c765139", "allowed": true}
2023-08-09T06:52:09Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-apps-emqx-io-v2beta1-emqx", "UID": "fc74cd9c-03ad-49d4-9ef0-e1994b8dac6b", "kind": "apps.emqx.io/v2beta1, Kind=EMQX", "resource": {"group":"apps.emqx.io","version":"v2beta1","resource":"emqxes"}}
2023-08-09T06:52:09Z	INFO	emqx-resource	validate update	{"name": "emqx-cluster"}
2023-08-09T06:52:09Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-apps-emqx-io-v2beta1-emqx", "code": 200, "reason": "", "UID": "fc74cd9c-03ad-49d4-9ef0-e1994b8dac6b", "allowed": true}
2023-08-09T06:52:10Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-apps-emqx-io-v2beta1-emqx", "UID": "6d9b2730-7e5d-4f57-a107-c64e1ee8df1d", "kind": "apps.emqx.io/v2beta1, Kind=EMQX", "resource": {"group":"apps.emqx.io","version":"v2beta1","resource":"emqxes"}}
2023-08-09T06:52:10Z	INFO	emqx-resource	default	{"name": "emqx-cluster"}
2023-08-09T06:52:10Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-apps-emqx-io-v2beta1-emqx", "code": 200, "reason": "", "UID": "6d9b2730-7e5d-4f57-a107-c64e1ee8df1d", "allowed": true}
2023-08-09T06:52:10Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-apps-emqx-io-v2beta1-emqx", "UID": "c59cf613-1dc6-4763-a923-d492aa169822", "kind": "apps.emqx.io/v2beta1, Kind=EMQX", "resource": {"group":"apps.emqx.io","version":"v2beta1","resource":"emqxes"}}
2023-08-09T06:52:10Z	INFO	emqx-resource	validate create	{"name": "emqx-cluster"}
2023-08-09T06:52:10Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-apps-emqx-io-v2beta1-emqx", "code": 200, "reason": "", "UID": "c59cf613-1dc6-4763-a923-d492aa169822", "allowed": true}
2023-08-09T06:52:13Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411535"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:14Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:15Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:15Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:16Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:16Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:17Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:17Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:18Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:18Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:19Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:19Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:20Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.240.76:18083/api/v5/nodes: failed to request API: Get \"http://10.240.240.76:18083/api/v5/nodes\": dial tcp 10.240.240.76:18083: connect: connection refused"}
2023-08-09T06:52:20Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.240.76:18083/api/v5/nodes: failed to request API: Get \"http://10.240.240.76:18083/api/v5/nodes\": dial tcp 10.240.240.76:18083: connect: connection refused"}
2023-08-09T06:52:21Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:21Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:22Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.240.76:18083/api/v5/nodes: failed to request API: Get \"http://10.240.240.76:18083/api/v5/nodes\": dial tcp 10.240.240.76:18083: connect: connection refused"}
2023-08-09T06:52:23Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.240.76:18083/api/v5/nodes: failed to request API: Get \"http://10.240.240.76:18083/api/v5/nodes\": dial tcp 10.240.240.76:18083: connect: connection refused"}
2023-08-09T06:52:24Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
2023-08-09T06:52:24Z	DEBUG	events	Warning	{"object": {"kind":"EMQX","namespace":"dev","name":"emqx-cluster","uid":"d832dab2-d3c2-4c7b-a571-b9dd135b602f","apiVersion":"apps.emqx.io/v2beta1","resourceVersion":"930411589"}, "reason": "FailedToGetNodeStatuses", "message": "failed to get node statues by API: failed to get API http://10.240.241.99:18083/api/v5/nodes: failed to request API: Get \"http://10.240.241.99:18083/api/v5/nodes\": dial tcp 10.240.241.99:18083: connect: connection refused"}
```

**Comment by Rory-Z** [comment]
It's strange. It seems that the EMQX container is ready, but does the log of EMQX Operator still show that the request is being rejected?

**Comment by tollercode** [comment]
No, the logs stop. So Operator is able to reach pods now and find the cluster nodes. Still the readyness gate is not fullfilled

**Comment by tollercode** [comment]
No sadly no success yet. I will try to completely recreate it

**Comment by Rory-Z** [comment]
> No sadly no success yet. I will try to completely recreate it

Ok, Any update please let me know

**Comment by tollercode** [comment]
@Rory-Z nothing working. 
My env:
- AKS: 1.24.9
- EMQX-EE: 5.1.1
- 2 Core Nodes

I will give up now and revert back to a working setup with 5.0.23.

**Comment by Rory-Z** [comment]
@tollercode I am very sorry. Please let me know your latest EMQX customer resource YAML file, I will work it.

**Comment by martinzima** [comment]
Today, we tried upgrading the operator to 2.2.0 in our dev cluster and hit the exact same issue (failing readiness gates won't let the StatefulSet fully come up, _failed to get node statues by API_ errors, etc.). After fiddling with different configurations for a while trying to pinpoint the moment when it stops working I finally found out it only happens when we create the EMQX object from Git using Flux (we are doing gitops for our configs). By simply by looking at the differences in EMQX object YAMLs (when using Flux vs. creating it directly) it seems to me that the EMQX operator fails to update some metadata (e.g. annotations.apps.emqx.io/last-emqx-configuration is missing) - I have no idea if this might be the reason or a just a symptom.
Nevertheless, everything was working fine before with version 2.1.1. We are using GKE 1.26.5 and the OSS version of EMQX.

**Comment by mariusstaicu** [comment]
[](url)Same issue for me when I update from 2.1.4 to 2.2.0 on emqx version 5.1.1, using k8s on GKE version 1.25
Pods seem ready, are running, but the statefulset does not show them available:

![Screenshot from 2023-08-10 14-48-03](https://github.com/emqx/emqx-operator/assets/9932238/5671dd2c-d9e8-4596-aaad-5b2c1ca0090f)

Readiness gates in the pods:

![Screenshot from 2023-08-10 14-52-33](https://github.com/emqx/emqx-operator/assets/9932238/5e644afa-c08d-4b5c-ac0f-f8156dea306c)

If I check the cluster status:

```
emqx@emqx-core-74cfbd88b6-0:/opt/emqx$ emqx_ctl cluster status
Cluster status: #{running_nodes =>
                      ['emqx@emqx-core-0.emqx-headless.infrastructure.svc.cluster.local',
                       'emqx@emqx-core-1.emqx-headless.infrastructure.svc.cluster.local',
                       'emqx@emqx-core-74cfbd88b6-0.emqx-headless.infrastructure.svc.cluster.local',
                       'emqx@emqx-core-74cfbd88b6-1.emqx-headless.infrastructure.svc.cluster.local'],
                  stopped_nodes => []}
emqx@emqx-core-74cfbd88b6-0:/opt/emqx$
```

**Comment by Rory-Z** [comment]
Hi @martinzima @mariusstaicu Could you please try `2.2.1-rc.3` ? You can install it by Helm like this:
```
helm upgrade --install emqx-operator emqx/emqx-operator \
  --namespace emqx-operator-system \
  --create-namespace \
  --version 2.2.1-rc.3
```
We have fixed some issues, but I'm not sure if your issue is included.

**Comment by mariusstaicu** [comment]
Tried it but it is still the same. Also tried to add --zap-devel=true to operator logs, but I don't see any debug log.
Maybe I did it wrong ?

![Screenshot from 2023-08-11 09-53-23](https://github.com/emqx/emqx-operator/assets/9932238/40507859-9f36-4f48-a956-f9e384db308b)

**Comment by Rory-Z** [comment]
@mariusstaicu Could you please deploy new EMQX cluster ? I see your EMQX nodes is `['emqx@emqx-core-0.emqx-headless.infrastructure.svc.cluster.local',
                       'emqx@emqx-core-1.emqx-headless.infrastructure.svc.cluster.local',
                       'emqx@emqx-core-74cfbd88b6-0.emqx-headless.infrastructure.svc.cluster.local',
                       'emqx@emqx-core-74cfbd88b6-1.emqx-headless.infrastructure.svc.cluster.local'],`, looks `emqx@emqx-core-1.emqx-headless.infrastructure.svc.cluster.local` is a v2alpha1 customer resource.

**Comment by tollercode** [comment]
Tried today with 2.2.1-rc.3. Same observation. Not ready and no debug logs on Controller.

**Comment by mariusstaicu** [comment]
> @mariusstaicu Could you please deploy new EMQX cluster ? I see your EMQX nodes is `['emqx@emqx-core-0.emqx-headless.infrastructure.svc.cluster.local', 'emqx@emqx-core-1.emqx-headless.infrastructure.svc.cluster.local', 'emqx@emqx-core-74cfbd88b6-0.emqx-headless.infrastructure.svc.cluster.local', 'emqx@emqx-core-74cfbd88b6-1.emqx-headless.infrastructure.svc.cluster.local'],`, looks `emqx@emqx-core-1.emqx-headless.infrastructure.svc.cluster.local` is a v2alpha1 customer resource.

Ok, this means deleting old nodes manually ? When I upgraded the operator, it started creating a new statefulset along the old one. I thought it will delete the old nodes after new nodes are fully up.

**Comment by Rory-Z** [comment]
@mariusstaicu Yes, please deleting old nodes manually, or you can just create a new cluster for test deploy

**Comment by Rory-Z** [comment]
@tollercode I know the reason now, it's a stupid mistake, and I will fix it. And before it, you can manually copy the label of EMQX to `coreTemplate.labels` and `replicantTemplate.labels` to fix it.

**Comment by martinzima** [comment]
> Hi @martinzima @mariusstaicu Could you please try `2.2.1-rc.3` ? You can install it by Helm like this:

Tried that, but the issue persists. Furthermore, upgrading to the RC version created a new ReplicatSet and the EMQX changed its state to ReplicantNodesProgressing, even though I have set it to have 0 replicants (not sure if this is expected).

**Comment by Rory-Z** [comment]
> @tollercode I know the reason now, it's a stupid mistake, and I will fix it. And before it, you can manually copy the label of EMQX and add to `coreTemplate.labels` and `replicantTemplate.labels` to fix it.

@martinzima Could you please try this ? If you don't want deploy replicant node, you can delete `replicantTemplate` in YAML file.

**Comment by mariusstaicu** [comment]
Ok @Rory-Z, now that I deleted the old nodes I have the same problem with readiness probe failing.

![Screenshot from 2023-08-11 15-52-35](https://github.com/emqx/emqx-operator/assets/9932238/defa606d-2dcd-4822-bd60-45634f387e20)

Which labels to add manually to coreTemplate ?

**Comment by mariusstaicu** [comment]
Indeed, it works for me also, thanks @tollercode, @Rory-Z

**Comment by Rory-Z** [comment]
Great, thanks @tollercode @mariusstaicu, let me fix this.

I have conceived two repair solutions:
+ one of which has a smaller impact on the existing deployment. It simply uses a fixed Labels key when searching for Pods, like `apps.emqx.io/instance`. It can fix the current problem.
+ Based on scheme one, I want to delete the existing default webhook and validate webhook. This change will be significant. If deployed with 2.2.0, upgrading to 2.2.1 will trigger a blue-green release once.

Because there are not many deployments of version 2.2.0, there is now a time window for me to delete the default webhook and validate webhook. Do you have any thoughts on this?

**Comment by Rory-Z** [comment]
> I would prefer the 2nd option, as I agree that most people might still operate with a version below 2.2.0 of the operator.
From my perspective, most people would probably prefer a clean 2.2.x version.

I think so, let's do it !

**Comment by Rory-Z** [comment]
Hi guys @tollercode @mariusstaicu @martinzima @clive-jevons , the EMQX Operator 2.2.1 is released, could you please try it.

**Comment by martinzima** [comment]
@Rory-Z Great, 2.2.1 works for me flawlessly now. Thank you!

**Comment by mariusstaicu** [comment]
@Rory-Z works great, haven't found anything wrong yet, I will test it more today.

**Comment by mariusstaicu** [comment]
The only issue that I can find is that, when you have replicas: 0 for replicants the emqx resource is showing status: ReplicantNodesProgressing and is stuck in that state. 
This is a minor issue and I'm not sure if it impacts anything, otherwise everything is working fine.

**Comment by Rory-Z** [comment]
Hi @mariusstaicu thank you for your detailed feedback. 

> The only issue that I can find is that, when you have replicas: 0 for replicants the emqx resource is showing status: ReplicantNodesProgressing and is stuck in that state.

Yes, the status of EMQX custom resources is a finite state machine. If the number of replicant nodes equals 0, it will get stuck there.

Perhaps I should check the quantity of replicant nodes. If it equals 0, then it should be treated as a cluster with only Core nodes. However, I am not sure if I should do this.

In fact, due to some business logic of EMQX, the Operator may have difficulty handling the switch between a only Core node cluster and a Core + Replicant node cluster.

I want to know why you set the number of replicant nodes to 0 instead of directly deleting the replicant template?

Maybe can create a new issue to discussion about replicant node equal 0

> Also I noticed that on 2.2.x, when you change the pod template for cores, it creates new statefulsets and the old ones are gradually scaled down to 0. However, the old statefulsets are kept and not deleted. Is this the desired behavior ?

Yes, You can manually delete the old statefulsets. The purpose of keeping the old statefulset is to perform rollback work in certain situations (requiring some hacking operations).

**Comment by tollercode** [comment]
I can also confirm healthy cluster and no issues. Great work.

**Comment by Rory-Z** [comment]
Hi guys, looks 2.2.1 is work, I will close this issue, if you have any question, can reopen it any time.

**Comment by clive-jevons** [comment]
@Rory-Z huge thanks for the updates and the new version 😍🙏🏻

I was able to create a new EMQX broker cluster using the new versions 👍

However, I'm still unclear on how to upgrade from an existing setup using operator 2.14 / broker 5.0.23 to a setup using operator 2.2.1 / broker 5.1.3.

When I upgrade the operator first, it starts creating the new core and then replicant nodes, but never deletes the old core STS / replicant deployment.

When I upgrade the broker first, it never finishes upgrading because of the bug in operator 2.1.4.

🤔 

Could you please outline what the recommended procedure is? Thank you very much in advance 🙏🏻
